version: '2'
services:
    allianzquotemonogradle-app:
        image: allianzquotemonogradle
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://allianzquotemonogradle-mysql:3306/allianzquotemonogradle?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    allianzquotemonogradle-mysql:
        extends:
            file: mysql.yml
            service: allianzquotemonogradle-mysql
